#!/bin/bash
# fake_protoc is used in tests.
# It
# - dumps the args passed to it to stdout
#.- copies the last arg (if that's a file) beneath the --grpc_out dir

main() {
    echo $@  # first echo, the protoc tests need that.

    local proto_path=${!#}
    local out_dir=$(echo "$@" | sed 's/.*--grpc_out=\([^ ]*\).*/\1/')
    # fix out_dir in case protoc was run for the go plugin
    local out_dir=$(echo "$out_dir" | sed 's/.*--go_out=plugins=grpc:\([^ ]*\).*/\1/')
    echo "out_dir is $out_dir" 1>&2;
    local out_proto_path=${out_dir}/$proto_path
    local out_parent=$(dirname $out_proto_path)

    # no need to do a real copy; the test proto path may be fake, just touch it.
    mkdir -p -v $out_parent && echo "created parent of $out_proto_path" 1>&2;
    touch $out_proto_path
}

main "$@"
